name: Build and Release on Commit

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run build

      - name: GitHub CLI installieren
        run: sudo apt update && sudo apt install -y gh

      - name: Release erstellen aus "out"-Ordner
        run: |
          if [ ! -d out ] || [ -z "$(ls -A out)" ]; then
            echo "Ordner 'out' ist leer – Release wird nicht erstellt"
          else
            RELEASE_NAME="release-$(date +%Y%m%d%H%M%S)-${GITHUB_SHA::8}"
            gh release create "$RELEASE_NAME" --notes "Automatischer Release für Commit $GITHUB_SHA" --prerelease
            for FILE in out/*; do
              gh release upload "$RELEASE_NAME" "$FILE"
            done
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
