name: Build and Release on Commit

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run build

      - name: GitHub CLI installieren
        run: sudo apt update && sudo apt install -y gh

      - name: Build archivieren und Release erstellen
        run: |
          zip -r build.zip ./build
          RELEASE_NAME="release-$(date +%Y%m%d%H%M%S)"
          gh release create "$RELEASE_NAME" build.zip --notes "Automatischer Release für Commit $GITHUB_SHA" --prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
